// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @notice Canonical ZK Email proof payload.
/// @dev Field-for-field mirror of the `EmailProof` struct used across the ZK Email
///      ecosystem (`zkemail/email-tx-builder`), so that a verifier generated by the ZK
///      Email Registry is a drop-in for {IZKEmailVerifier} with no adapter layer.
///
///      `proof` is opaque `bytes`, which is what makes this interface agnostic to the
///      proving system: Circom/Groth16 and Noir/UltraHonk blueprints both fit.
struct EmailProof {
    /// @notice Sender's email domain, e.g. "gmail.com". Keyed against the DKIM registry.
    string domainName;
    /// @notice Hash of the DKIM public key that signed the email.
    bytes32 publicKeyHash;
    /// @notice Email timestamp. Some blueprints do not expose one; 0 means "unknown".
    uint256 timestamp;
    /// @notice The command string extracted from the email, with private spans masked.
    string maskedCommand;
    /// @notice Unique per-email value. The basis of replay protection.
    bytes32 emailNullifier;
    /// @notice Commitment to (email address, salt). A guardian identifier that never
    ///         reveals the address itself.
    bytes32 accountSalt;
    /// @notice Whether the account code exists, per the circuit's public output.
    bool isCodeExist;
    /// @notice The zero-knowledge proof itself.
    bytes proof;
}

/// @title IZKEmailVerifier
/// @notice Verifies that an {EmailProof} attests to a genuine DKIM-signed email.
/// @dev Deliberately narrow: this interface answers only "is this proof sound?".
///      Whether the DKIM key is *trusted*, whether the command is bound to the right
///      request, and whether the email has already been spent are all separate concerns
///      enforced by {DynamicSocialRecovery}. Verification alone is never authorization.
interface IZKEmailVerifier {
    /// @notice Byte length of the command field the circuit was compiled for.
    function commandBytes() external view returns (uint256);

    /// @notice Verify a ZK Email proof.
    /// @dev MUST NOT revert on an invalid proof; return `false` so callers can
    ///      distinguish rejection from an unrelated failure.
    /// @return True if and only if the proof is valid for the given public inputs.
    function verifyEmailProof(EmailProof calldata proof) external view returns (bool);
}
